import { CalendarPlus, Check, FileClock } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import Button from '../../components/common/Button.jsx'
import EmptyState from '../../components/common/EmptyState.jsx'
import Input from '../../components/common/Input.jsx'
import Select from '../../components/common/Select.jsx'
import StatusBadge from '../../components/common/StatusBadge.jsx'
import { LoadingState, AsyncError } from '../../components/common/AsyncMessage.jsx'
import PageShell from './PageShell.jsx'
import { leaveService } from '../../services/api.js'
import { formatDate } from '../../utils/formatters.js'

export default function Leave() {
  const [leaves, setLeaves] = useState(null); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [toast, setToast] = useState(''); const load = async () => { try { const response = await leaveService.getMine(); setLeaves(response.data || []) } catch { setError('We could not load your leave requests.') } }; useEffect(() => { load() }, []); const counts = useMemo(() => ({ Pending: leaves?.filter((item) => item.status === 'Pending').length || 0, Approved: leaves?.filter((item) => item.status === 'Approved').length || 0, Rejected: leaves?.filter((item) => item.status === 'Rejected').length || 0 }), [leaves]); const submit = async (payload) => { try { const response = await leaveService.create(payload); setLeaves((current) => [response.data, ...(current || [])]); setOpen(false); setToast('Leave request submitted successfully.'); setTimeout(() => setToast(''), 2500) } catch { setError('Unable to submit your leave request.') } }
  if (error && !leaves) return <PageShell eyebrow="Time away" title="Leave Management" description="Plan time away and review your requests."><AsyncError message={error} onRetry={load} /></PageShell>
  if (!leaves) return <PageShell eyebrow="Time away" title="Leave Management" description="Plan time away and review your requests."><LoadingState /></PageShell>
  return <PageShell eyebrow="Time away" title="Leave Management" description="Plan time away and review your requests."><div className="grid gap-4 sm:grid-cols-3">{Object.entries(counts).map(([label, value]) => <div key={label} className="rounded-2xl border border-[#e1e9e4] bg-white p-5"><p className="text-sm text-[#81908a]">{label}</p><p className="display-font mt-2 text-3xl">{value}</p></div>)}</div><section className="rounded-2xl border border-[#e1e9e4] bg-white p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#eef5d9] p-2.5 text-[#759329]"><CalendarPlus size={19} /></div><div><h3 className="display-font">Need time off?</h3><p className="text-sm text-[#81908a]">Submit a leave request for manager review.</p></div></div><Button onClick={() => setOpen(true)}><CalendarPlus size={16} />Apply Leave</Button></div></section><section><div className="mb-4 flex items-center gap-3"><FileClock className="text-[#759329]" size={19} /><h3 className="display-font text-lg">My requests</h3></div>{leaves.length ? <div className="overflow-x-auto rounded-2xl border border-[#e1e9e4] bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-[#e8efea] text-xs uppercase tracking-wider text-[#9aa9a3]"><tr><th className="p-4">Leave type</th><th className="p-4">Start date</th><th className="p-4">End date</th><th className="p-4">Remarks</th><th className="p-4">Status</th></tr></thead><tbody>{leaves.map((leave) => <tr key={leave.id} className="border-b border-[#f0f3f1] last:border-0"><td className="p-4 font-semibold">{leave.leaveType}</td><td className="p-4 text-[#718078]">{formatDate(leave.startDate)}</td><td className="p-4 text-[#718078]">{formatDate(leave.endDate)}</td><td className="p-4 text-[#718078]">{leave.remarks || '—'}{leave.status === 'Rejected' && leave.admin_comment && <p className="mt-1 text-xs text-[#a85142]">HR Comment: {leave.admin_comment}</p>}</td><td className="p-4"><StatusBadge status={leave.status} /></td></tr>)}</tbody></table></div> : <EmptyState title="No leave requests yet" description="Approved and previous leave requests will be listed here." />}</section>{open && <LeaveModal onClose={() => setOpen(false)} onSubmit={submit} />}{toast && <div className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-xl bg-[#17211f] px-4 py-3 text-sm font-semibold text-white"><Check size={16} className="text-[#d8ef69]" />{toast}</div>}</PageShell>
}
function LeaveModal({ onClose, onSubmit }) { const [form, setForm] = useState({ leaveType: 'Paid', startDate: '', endDate: '', remarks: '' }); const [loading, setLoading] = useState(false); const update = (field) => (event) => setForm({ ...form, [field]: event.target.value }); const submit = async (event) => { event.preventDefault(); if (form.endDate < form.startDate) return; setLoading(true); await onSubmit(form); setLoading(false) }; return <div className="fixed inset-0 z-40 flex items-center justify-center bg-[#17211f]/35 p-5"><form onSubmit={submit} className="w-full max-w-lg space-y-5 rounded-2xl bg-white p-6 shadow-2xl"><div><h2 className="display-font text-xl">Apply for leave</h2><p className="mt-1 text-sm text-[#81908a]">Your manager will review this request.</p></div><Select label="Leave type" options={['Paid', 'Sick', 'Unpaid']} value={form.leaveType} onChange={update('leaveType')} /><div className="grid gap-4 sm:grid-cols-2"><Input label="Start date" type="date" value={form.startDate} onChange={update('startDate')} required /><Input label="End date" type="date" value={form.endDate} onChange={update('endDate')} required /></div><label className="block space-y-2"><span className="text-sm font-semibold text-[#34413c]">Remarks</span><textarea value={form.remarks} onChange={update('remarks')} rows="3" className="w-full resize-none rounded-xl border border-[#dfe6e2] px-4 py-3 text-sm outline-none focus:border-[#8fae36]" placeholder="Add context for your manager" /></label><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={loading}>{loading ? 'Submitting...' : 'Submit Leave Request'}</Button></div></form></div> }
