import { CircleDollarSign, FileText, LockKeyhole } from 'lucide-react'
import { useEffect, useState } from 'react'
import EmptyState from '../../components/common/EmptyState.jsx'
import { LoadingState, AsyncError } from '../../components/common/AsyncMessage.jsx'
import PageShell from './PageShell.jsx'
import { payrollService } from '../../services/api.js'
import { formatCurrency } from '../../utils/formatters.js'

export default function Payroll() { const [payroll, setPayroll] = useState(null); const [loaded, setLoaded] = useState(false); const [error, setError] = useState(''); const load = async () => { try { const response = await payrollService.getMine(); setPayroll(response.data) } catch { setError('We could not load your salary information.') } finally { setLoaded(true) } }; useEffect(() => { load() }, []); if (!loaded) return <PageShell eyebrow="Compensation" title="My Salary" description="Your private compensation summary."><LoadingState /></PageShell>; if (error) return <PageShell eyebrow="Compensation" title="My Salary" description="Your private compensation summary."><AsyncError message={error} onRetry={load} /></PageShell>; return <PageShell eyebrow="Compensation" title="My Salary" description="Your private compensation summary.">{payroll ? <><section className="rounded-2xl bg-[#17211f] p-6 text-white sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm text-[#b8c7c0]">Net salary</p><p className="display-font mt-2 text-4xl">{formatCurrency(payroll.netSalary)}</p><p className="mt-2 text-sm text-[#9aa9a3]">Current salary structure</p></div><div className="rounded-xl bg-[#d8ef69] p-3 text-[#425612]"><CircleDollarSign size={22} /></div></div><div className="mt-8 h-px bg-[#33413c]" /><div className="mt-5 flex items-center gap-2 text-sm text-[#b8c7c0]"><LockKeyhole size={15} />Read only</div></section><section className="rounded-2xl border border-[#e1e9e4] bg-white p-6"><div className="mb-6 flex items-center gap-3 border-b border-[#e8efea] pb-5"><FileText className="text-[#759329]" size={19} /><div><h3 className="display-font">Salary breakdown</h3><p className="text-sm text-[#81908a]">Only your organization can change these values.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><SalaryRow label="Basic salary" value={payroll.basicSalary} /><SalaryRow label="Allowances" value={payroll.allowances} /><SalaryRow label="Deductions" value={payroll.deductions} /><SalaryRow label="Net salary" value={payroll.netSalary} strong /></div></section></> : <EmptyState title="Payroll unavailable" description="Salary information will appear here once payroll is connected." />}</PageShell> }
function SalaryRow({ label, value, strong }) { return <div className={`flex items-center justify-between rounded-xl bg-[#f7f9f8] p-4 ${strong ? 'font-bold text-[#507221]' : ''}`}><span className="text-sm text-[#718078]">{label}</span><span className="text-sm">{formatCurrency(value)}</span></div> }
