import { createElement, useEffect, useState } from 'react'
import { FileText, Mail, MapPin, Pencil, Phone, UserRound, X } from 'lucide-react'
import Badge from '../../components/common/Badge.jsx'
import Button from '../../components/common/Button.jsx'
import EmptyState from '../../components/common/EmptyState.jsx'
import Input from '../../components/common/Input.jsx'
import { LoadingState, AsyncError } from '../../components/common/AsyncMessage.jsx'
import PageShell from './PageShell.jsx'
import { employeeService, payrollService } from '../../services/api.js'
import { formatCurrency } from '../../utils/formatters.js'

export default function Profile() {
  const [employee, setEmployee] = useState(null); const [payroll, setPayroll] = useState(null); const [error, setError] = useState(''); const [editing, setEditing] = useState(false); const [toast, setToast] = useState('')
  const load = async () => { try { const [employeeResponse, payrollResponse] = await Promise.all([employeeService.getMe(), payrollService.getMine()]); setEmployee(employeeResponse.data); setPayroll(payrollResponse.data) } catch { setError('We could not load your profile.') } }
  useEffect(() => { load() }, [])
  const save = async (payload) => { const response = await employeeService.updateMe(payload); setEmployee(response.data); setEditing(false); setToast('Profile updated successfully'); setTimeout(() => setToast(''), 2500) }
  if (error) return <PageShell eyebrow="Employee record" title="My profile" description="Your personal and work information."><AsyncError message={error} onRetry={load} /></PageShell>
  if (!employee) return <PageShell eyebrow="Employee record" title="My profile" description="Your personal and work information."><LoadingState /></PageShell>
  return <PageShell eyebrow="Employee record" title="My profile" description="Your personal and work information, all in one place."><div className="grid gap-5 lg:grid-cols-[280px_1fr]"><section className="rounded-2xl border border-[#e1e9e4] bg-white p-6 text-center"><div className="mx-auto flex h-24 w-24 items-center justify-center overflow-hidden rounded-3xl bg-[#d8ef69] text-2xl font-extrabold text-[#425612]">{employee.profilePicture ? <img src={employee.profilePicture} alt="Profile" className="h-full w-full object-cover" /> : 'AM'}</div><h3 className="display-font mt-5 text-xl">{employee.name}</h3><p className="mt-1 text-sm text-[#81908a]">{employee.position}</p><p className="mt-2 text-xs text-[#9aa9a3]">{employee.id}</p><Badge tone="success">Active employee</Badge><div className="mt-7 space-y-3 text-left text-sm text-[#718078]"><p className="flex items-center gap-3"><Mail size={16} />{employee.email}</p><p className="flex items-center gap-3"><MapPin size={16} />{employee.address || 'No address added'}</p><p className="flex items-center gap-3"><Phone size={16} />{employee.phone || 'No phone added'}</p></div><Button className="mt-7 w-full" onClick={() => setEditing(true)}><Pencil size={16} />Edit profile</Button></section><div className="space-y-5"><DetailSection title="Personal details" icon={UserRound}><Detail label="Name" value={employee.name} /><Detail label="Email" value={employee.email} /><Detail label="Phone" value={employee.phone || 'Not provided'} /><Detail label="Address" value={employee.address || 'Not provided'} /></DetailSection><DetailSection title="Job details" icon={BriefcaseIcon}><Detail label="Employee ID" value={employee.id} /><Detail label="Job position" value={employee.position} /><Detail label="Role" value={employee.role} /></DetailSection><DetailSection title="Salary structure" icon={WalletIcon}><Detail label="Basic salary" value={payroll ? formatCurrency(payroll.basicSalary) : 'Unavailable'} /><Detail label="Allowances" value={payroll ? formatCurrency(payroll.allowances) : 'Unavailable'} /><Detail label="Deductions" value={payroll ? formatCurrency(payroll.deductions) : 'Unavailable'} /><Detail label="Net salary" value={payroll ? formatCurrency(payroll.netSalary) : 'Unavailable'} /></DetailSection><DetailSection title="Documents" icon={FileText}>{<EmptyState title="No documents available" description="Documents shared by your organization will appear here." />}</DetailSection></div></div>{editing && <EditModal employee={employee} onClose={() => setEditing(false)} onSave={save} />}{toast && <div className="fixed bottom-5 right-5 z-50 rounded-xl bg-[#17211f] px-4 py-3 text-sm font-semibold text-white">{toast}</div>}</PageShell>
}
function DetailSection({ title, icon, children }) { return <section className="rounded-2xl border border-[#e1e9e4] bg-white p-6"><div className="mb-6 flex items-center gap-3 border-b border-[#e8efea] pb-5">{createElement(icon, { size: 19, className: 'text-[#8aa82f]' })}<h3 className="display-font">{title}</h3></div><div className="grid gap-5 sm:grid-cols-2">{children}</div></section> }
function Detail({ label, value }) { return <div><p className="text-xs font-bold uppercase tracking-wider text-[#9aa9a3]">{label}</p><p className="mt-2 text-sm font-semibold text-[#34413c]">{value}</p></div> }
function EditModal({ employee, onClose, onSave }) { const [phone, setPhone] = useState(employee.phone || ''); const [address, setAddress] = useState(employee.address || ''); const [picture, setPicture] = useState(employee.profilePicture || ''); const [loading, setLoading] = useState(false); const submit = async (event) => { event.preventDefault(); setLoading(true); await onSave({ phone, address, profilePicture: picture }); setLoading(false) }; const fileChange = (event) => { const file = event.target.files?.[0]; if (file) { const reader = new FileReader(); reader.onload = () => setPicture(reader.result); reader.readAsDataURL(file) } }; return <div className="fixed inset-0 z-40 flex items-center justify-center bg-[#17211f]/35 p-5"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between"><div><h2 className="display-font text-xl">Edit profile</h2><p className="mt-1 text-sm text-[#81908a]">Only contact details can be changed.</p></div><button onClick={onClose} aria-label="Close modal"><X size={19} /></button></div><form onSubmit={submit} className="space-y-5"><Input label="Phone" value={phone} onChange={(event) => setPhone(event.target.value)} /><Input label="Address" value={address} onChange={(event) => setAddress(event.target.value)} /><label className="block space-y-2 text-sm font-semibold">Profile picture<input type="file" accept="image/*" onChange={fileChange} className="mt-2 block w-full text-sm text-[#81908a]" /></label><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={loading}>{loading ? 'Saving...' : 'Save changes'}</Button></div></form></div></div> }
function BriefcaseIcon(props) { return <UserRound {...props} /> }
function WalletIcon(props) { return <span {...props}>₹</span> }
