import { ArrowRight, CheckCircle2, Eye, EyeOff } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import Button from '../../components/common/Button.jsx'
import Input from '../../components/common/Input.jsx'
import { useAuth } from '../../hooks/useAuth.js'
import { AuthFrame } from './Login.jsx'

export default function Register() {
  const [form, setForm] = useState({ employeeId: '', email: '', password: '', confirmPassword: '' }); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(false); const { register } = useAuth(); const navigate = useNavigate()
  const update = (field) => (event) => setForm({ ...form, [field]: event.target.value })
  const submit = async (event) => { event.preventDefault(); setError(''); if (!form.employeeId.trim()) return setError('Employee ID is required.'); if (!/^\S+@\S+\.\S+$/.test(form.email)) return setError('Enter a valid work email.'); if (form.password.length < 8) return setError('Password must be at least 8 characters.'); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); setLoading(true); try { await register({ ...form, role: 'EMPLOYEE' }); setSuccess(true); setTimeout(() => navigate('/employee/dashboard', { replace: true }), 700) } catch { setError('Unable to create your account right now.') } finally { setLoading(false) } }
  return <AuthFrame title="Create your account" description="Set up your Dayflow workspace access." sideTitle="Your best work starts here." sideCopy="Bring your people, rhythm, and progress into one thoughtful workspace."><form onSubmit={submit} className="space-y-5"><Input label="Employee ID" placeholder="EMP-2048" value={form.employeeId} onChange={update('employeeId')} required /><Input label="Work email" type="email" placeholder="you@company.com" value={form.email} onChange={update('email')} required /><label className="block space-y-2"><span className="text-sm font-semibold text-[#34413c]">Password</span><span className="relative block"><input className="w-full rounded-xl border border-[#dfe6e2] bg-white px-4 py-3 pr-12 text-sm outline-none focus:border-[#8fae36] focus:ring-4 focus:ring-[#d8ef69]/25" type={show ? 'text' : 'password'} value={form.password} onChange={update('password')} placeholder="At least 8 characters" required /><button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(!show)} className="absolute right-3 top-3 text-[#81908a]">{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></span></label>{form.password && <div className="flex items-center gap-2 text-xs font-semibold text-[#759329]"><CheckCircle2 size={15} />{form.password.length >= 8 ? 'Strong enough to use' : 'Use at least 8 characters'}</div>}<Input label="Confirm password" type="password" value={form.confirmPassword} onChange={update('confirmPassword')} required />{error && <p className="text-sm text-[#a85142]">{error}</p>}{success && <p className="text-sm font-semibold text-[#507221]">Account created. Taking you to your workspace...</p>}<Button className="w-full" type="submit" disabled={loading || success}>{loading ? 'Creating account...' : 'Create account'} {!loading && <ArrowRight size={17} />}</Button><p className="text-center text-sm text-[#81908a]">Already have an account? <Link className="font-bold text-[#6f8d27]" to="/login">Sign in</Link></p></form></AuthFrame>
}
